apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-jisung
spec:
  destination:
    namespace: hitachi-pj-hcsgenai2-usermanaged
    server: https://kubernetes.default.svc
  source:
    path: k8s
    repoURL: https://github.com/Psung10/sung10.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
